### PR TITLE
Feat/add date filter at rule level

### PR DESCRIPTION
**Pull request by piraveen**

### CODE REVIEW

**Comment by ahochsteger** [comment]
@piraveen thanks for your contribution.
I do not really see the benefit for adding another rule property `newerThan` over just adding `newer_than:3m` to the existing rule property `filter`.
I tend to keep implementation complexity low and not merge this PR unless you can give me a good reason for added benefit which I currently don't see.

**Comment by ahochsteger** [comment]
@piraveen, sorry, I see now that you were refering to the already existing property`newerThan` that is not available on the rule level and not introducing a completely new property. That of course makes sense.
If you update the PR I can merge it.

**Comment by piraveen** [comment]
@ahochsteger sorry for the late response. Yes indeed, I was refering to the already existing property `newerThan`. 

PR conflict has been fixed.

**Comment by ahochsteger** [comment]
@piraveen thanks for your contribution, looks good to me.

**Pull request merged**
